
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author julianob
 */
public class DetalhesDaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form DetalhesDaConsulta
     */
    private boolean consultaRealizada = false;
    private JTable Tabela;
    private int selectedRow;
    private List<String> teste = new ArrayList<>();
    private TelaInicial telaInicial;

    public DetalhesDaConsulta(JTable tabela, TelaInicial telaInicial, int selectedRow) {
        this.telaInicial = telaInicial;
        this.Tabela = tabela;
        this.selectedRow = selectedRow;
        initComponents();
      
        String valorColuna = (String) Tabela.getValueAt(selectedRow, 5);
        if (valorColuna=="sim") {
            BotaoConsultaRealizad.setSelected(true);
            BotaoConsultaRealizad.setEnabled(false);
        } else {
            BotaoConsultaRealizad.setEnabled(true);
        }

    }

    /**
     * se This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
//        private void preencherCampos() {
//        String nome = Tabela.getValueAt(selectedRow, 0).toString();
//     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotaoConsultaRealizad = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtexto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        BotaoFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotaoConsultaRealizad.setText("ConsultaRealizada");
        BotaoConsultaRealizad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultaRealizadActionPerformed(evt);
            }
        });
        BotaoConsultaRealizad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BotaoConsultaRealizadKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Detalhes da Consulta");

        Jtexto.setColumns(20);
        Jtexto.setRows(5);
        Jtexto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JtextoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Jtexto);

        jLabel2.setText("Receitas e observações:");

        BotaoFinalizar.setText("Finalizar");
        BotaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BotaoFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoConsultaRealizad))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BotaoConsultaRealizad)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(BotaoFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFinalizarActionPerformed
        selectedRow = Tabela.getSelectedRow();
        String valorColuna = "";

        if (consultaRealizada) {
            JOptionPane.showMessageDialog(this, "A consulta já foi realizada.");
            return;
        }

        if (Jtexto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um texto nas observações.");
            return;
        }
if(BotaoConsultaRealizad.isSelected()){
        valorColuna = "sim";
        telaInicial.editarLinhaSelecionada(Tabela, selectedRow, valorColuna);
        consultaRealizada = true;
        BotaoConsultaRealizad.setSelected(true);       
        BotaoConsultaRealizad.setEnabled(false);
        BotaoFinalizar.setEnabled(false);
        
        JOptionPane.showMessageDialog(this, "Consulta finalizada com sucesso!");
}else{
        valorColuna = "nao";
        telaInicial.editarLinhaSelecionada(Tabela, selectedRow, valorColuna);
        consultaRealizada = false;
 
        BotaoFinalizar.setEnabled(false);
        
        JOptionPane.showMessageDialog(this, "a consulta nao aconteceu");

}
        this.dispose();


    }//GEN-LAST:event_BotaoFinalizarActionPerformed

    private void BotaoConsultaRealizadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultaRealizadActionPerformed
        selectedRow = Tabela.getSelectedRow();
        TelaInicial telaInicial = new TelaInicial();

        String valorColuna = (String) Tabela.getValueAt(selectedRow, 5);

        if ("sim".equals(valorColuna)) {
            BotaoConsultaRealizad.setSelected(true);
            BotaoConsultaRealizad.setEnabled(false);
            consultaRealizada = true;
            BotaoFinalizar.setEnabled(false);
        } else {
            BotaoConsultaRealizad.setEnabled(true);
            consultaRealizada = false;
            BotaoFinalizar.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoConsultaRealizadActionPerformed

    private void BotaoConsultaRealizadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoConsultaRealizadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoConsultaRealizadKeyTyped

    private void JtextoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JtextoAncestorAdded

    }//GEN-LAST:event_JtextoAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesDaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesDaConsulta(null, null, 5).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotaoConsultaRealizad;
    private javax.swing.JButton BotaoFinalizar;
    private javax.swing.JTextArea Jtexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
