
import Models.Paciente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author julianob
 */
public class TelaInicial extends javax.swing.JFrame {

int linhaSelecionada;
    private DefaultTableModel model;
    private List<String> teste = new ArrayList<>();
    /**
     * Creates new form TelaInicial
     */
    private List<Object[]> dados;

    public TelaInicial() {
        initComponents();
        model = (DefaultTableModel) Tabelas.getModel();
        dados = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BotaoNovaConsulta = new javax.swing.JButton();
        BotaoFinalizarConsulta = new javax.swing.JButton();
        BotaoExcluirConsulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "CPF", "Telefone", "Data", "Ja é paciente?", "Consulta Realizada"
            }
        ));
        jScrollPane1.setViewportView(Tabelas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Boas Vindas ao sistema de agendamento");

        BotaoNovaConsulta.setText("Nova Consulta");
        BotaoNovaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovaConsultaActionPerformed(evt);
            }
        });

        BotaoFinalizarConsulta.setText("Finalizar Consulta");
        BotaoFinalizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFinalizarConsultaActionPerformed(evt);
            }
        });

        BotaoExcluirConsulta.setText("Excluir Consulta");
        BotaoExcluirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirConsultaActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addComponent(BotaoNovaConsulta)
                        .addGap(43, 43, 43)
                        .addComponent(BotaoExcluirConsulta)
                        .addGap(32, 32, 32)
                        .addComponent(BotaoFinalizarConsulta)
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoFinalizarConsulta)
                    .addComponent(BotaoExcluirConsulta)
                    .addComponent(BotaoNovaConsulta)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoNovaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovaConsultaActionPerformed

        CadastroConsulta c = new CadastroConsulta(this);
        c.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_BotaoNovaConsultaActionPerformed

    private void BotaoFinalizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFinalizarConsultaActionPerformed

    if (linhaSelecionada != -1) {
        Object[] dadosLinha = new Object[model.getColumnCount()];
        for (int coluna = 0; coluna < model.getColumnCount(); coluna++) {
            dadosLinha[coluna] = model.getValueAt(linhaSelecionada, coluna);
        }

        DetalhesDaConsulta detalhesDaConsulta = new DetalhesDaConsulta(Tabelas, this, linhaSelecionada);
        detalhesDaConsulta.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada.");
    }


    }//GEN-LAST:event_BotaoFinalizarConsultaActionPerformed

    private void BotaoExcluirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirConsultaActionPerformed
        linhaSelecionada = Tabelas.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "por favor selecione uma linha");
        } else {
            ((DefaultTableModel) Tabelas.getModel()).removeRow(linhaSelecionada);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_BotaoExcluirConsultaActionPerformed

    public void adicionarPessoa(Paciente pessoa) {
        Object[] linha = new Object[]{pessoa.getNome(), pessoa.getCpf(), pessoa.getTelefone(), pessoa.getData(), pessoa.getJaEraPaciente()};
        dados.add(linha);
        model.addRow(linha);
        System.out.println("");  }
 public void editarLinhaSelecionada(JTable tabela, int linhaSelecionada,String valorColuna) {
    if (linhaSelecionada >= 0 && linhaSelecionada < tabela.getRowCount()) {
      
    
        tabela.setValueAt(valorColuna, linhaSelecionada, 5);
        System.out.println("tem que atualiza a tabela");
    } else {
        System.out.println(" nao deu");
    } 
      
}

    public JTable getTable() {
        return Tabelas;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaInicial().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoExcluirConsulta;
    private javax.swing.JButton BotaoFinalizarConsulta;
    private javax.swing.JButton BotaoNovaConsulta;
    private javax.swing.JTable Tabelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
